apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.org.linuxfoundation.demos
spec:
  group: org.linuxfoundation.demos
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                database:
                  type: object
                  properties:
                    name:
                      type: string
                    port:
                      type: integer
                    host:
                      type: string
                    user:
                      type: string
                    passwordSecret:
                      type: string
                schedule:
                  type: string
                retention:
                  type: integer
                storageLocation:
                  type: string
            status:
              type: object
              properties:
                lastBackupTakenAt:
                  type: string
      subresources:
        status: { }
  names:
    kind: Backup
    plural: backups
  scope: Namespaced